name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Copy build files to EC2 (to /tmp directory)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: build/*
          target: /tmp/react-app-temp
          strip_components: 1
          port: 22

      - name: SSH into EC2 and move files to /var/www/html/react-app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/react-app
            sudo rm -rf /var/www/html/react-app/*
            sudo cp -r /tmp/react-app-temp/* /var/www/html/react-app/
            sudo chown -R www-data:www-data /var/www
