name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies & Build React App
        run: |
          git pull origin main  # Ensure latest code is pulled
          npm install
          npm run build

      - name: Transfer Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "build"
          target: "/var/www/html/react-app"
          strip_components: 1

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/react-app/*  # Remove old files
            sudo mv /var/www/html/react-app/build/* /var/www/html/react-app/
            sudo systemctl restart nginx
            sudo systemctl status nginx
